Repository BelkacemYerfa/shadcn-extension, pull requests merged in 2024-03, with the labels that each got.

#16 Feat : add the full doc page for the most of component besides file upload
  .vscode/settings.json
  content/docs/breadcrumb.mdx
  content/docs/carousel.mdx
  content/docs/file-upload.mdx
  content/docs/image-carousel-upload.mdx
  content/docs/multi-select.mdx
  content/docs/otp-input.mdx
  content/docs/tree-view.mdx
  next.config.mjs
  package-lock.json
  package.json
  src/__registry__/index.tsx
  src/app/components/page.tsx
  src/app/examples/page.tsx
  src/app/layout.tsx
  src/app/playground/page.tsx
  src/components/analytics.tsx
  src/components/cards/component-card.tsx
  src/components/component-preview.tsx
  src/components/copy-button.tsx
  src/components/doc-breadcrumb.tsx
  src/components/icons.tsx
  src/components/layouts/site-header.tsx
  src/components/layouts/toc.tsx
  src/components/playground/playground-preview.tsx
  src/components/playground/playground.tsx
  src/components/tables/mdx-table.tsx
  src/components/toc.tsx
  src/components/ui/form.tsx
  src/env.ts
  src/lib/element-parser.ts
  src/lib/events.ts
  src/registry/components.ts
  src/registry/default/example/breadcrumb-demo.tsx
  src/registry/default/example/carousel-demo.tsx
  src/registry/default/example/carousel/carousel-indicator.tsx
  src/registry/default/example/carousel/carousel-orientation.tsx
  src/registry/default/example/carousel/carousel-plugin.tsx
  src/registry/default/example/file-upload-demo.tsx
  src/registry/default/example/image-carousel-upload-demo.tsx
  src/registry/default/example/multi-select-demo.tsx
  src/registry/default/example/multi-select/multi-select-state.tsx
  src/registry/default/example/multi-select/multi-select-zod.tsx
  src/registry/default/example/otp-input-demo.tsx
  src/registry/default/example/otp-input/otp-input-zod.tsx
  src/registry/default/example/tree-view-demo.tsx
  src/registry/default/example/tree-view/tree-view-builtin-expand.tsx
  src/registry/default/example/tree-view/tree-view-builtin-indicator.tsx
  src/registry/default/example/tree-view/tree-view-builtin-select.tsx
  src/registry/default/example/tree-view/tree-view-guide.tsx
  src/registry/default/extension/breadcrumb.tsx
  src/registry/default/extension/carousel.tsx
  src/registry/default/extension/multi-select.tsx
  src/registry/default/extension/otp-input.tsx
  src/registry/default/extension/tree-view-api.tsx
  src/registry/default/extension/tree-view.tsx
  src/registry/schema.ts
  src/script/registry-builder.ts
Labels: documentation

#21 feat : add the new example for breadcrumb , feat : add mobile menu for navigation
  content/docs/tree-view.mdx
  package-lock.json
  package.json
  src/app/examples/page.tsx
  src/app/page.tsx
  src/components/banner.tsx
  src/components/layouts/toc.tsx
  src/components/playground/playground-preview.tsx
  src/components/playground/playground.tsx
  src/lib/element-parser.ts
  src/registry/default/example/tree-view/tree-view-guide.tsx
  src/registry/default/extension/breadcrumb.tsx
  src/registry/default/extension/file-upload.tsx
  src/registry/default/extension/tree-view-api.tsx
Labels: documentation, enhancement

#23 👌 IMPROVE(carousel): fix missing classname, use data attribute for thumbs
  src/registry/default/extension/carousel.tsx
Labels: enhancement
